export const navigationItems = [{
        id: "dashboard",
        label: "Главная",
        path: "/",
        icon: "🏠",
        end: true,
        badge: null,
        roles: ["admin", "moderator"],
    },
    {
        id: "places",
        label: "Объявления",
        path: "/places",
        icon: "📍",
        badge: null,
        roles: ["admin", "moderator"],
    },
    {
        id: "users",
        label: "Пользователи",
        path: "/users",
        icon: "👥",
        badge: null,
        roles: ["admin", "moderator"],
    },
    {
        id: "reports",
        label: "Жалобы",
        path: "/reports",
        icon: "🚩",
        badge: null,
        roles: ["admin", "moderator"],
    },
    {
        id: "reviews",
        label: "Отзывы",
        path: "/reviews",
        icon: "⭐",
        badge: null,
        roles: ["admin", "moderator"],
    },
    {
        id: "appeals",
        label: "Обращения",
        path: "/appeals",
        icon: "📨",
        badge: null,
        roles: ["admin", "moderator"],
    },
    {
        id: "categories",
        label: "Категории",
        path: "/categories",
        icon: "🗂️",
        badge: null,
        roles: ["admin"],
    },
    {
        id: "place-types",
        label: "Типы объектов",
        path: "/place-types",
        icon: "🏷️",
        badge: null,
        roles: ["admin"],
    },
    {
        id: "attributes",
        label: "Характеристики",
        path: "/attributes",
        icon: "⚙️",
        badge: null,
        roles: ["admin", "moderator"],
    },
    {
        id: "dictionaries",
        label: "Справочники",
        path: "/dictionaries",
        icon: "📚",
        badge: null,
        roles: ["admin", "moderator"],
    },
    {
        id: "plans",
        label: "Тарифы",
        path: "/plans",
        icon: "💼",
        badge: null,
        roles: ["admin"],
    },
    {
        id: "payments",
        label: "Платежи",
        path: "/payments",
        icon: "💳",
        badge: null,
        roles: ["admin"],
    },
    {
        id: "mailings",
        label: "Рассылки",
        path: "/mailings",
        icon: "✉️",
        badge: null,
        roles: ["admin"],
    },
    {
        id: "statistics",
        label: "Статистика",
        path: "/statistics",
        icon: "📊",
        badge: null,
        roles: ["admin", "moderator"],
    },
    {
        id: "moderator-logs",
        label: "Логи модераторов",
        path: "/moderator-logs",
        icon: "🧾",
        badge: null,
        roles: ["admin"],
    },
    {
        id: "settings",
        label: "Настройки сайта",
        path: "/settings",
        icon: "🛠️",
        badge: null,
        roles: ["admin"],
    },
];

export const pageTitles = navigationItems.reduce((acc, item) => {
    acc[item.path] = item.label;
    return acc;
}, {});